name: Deploy to DigitalOcean Droplet
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy Docker Compose files to droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_SSH_HOST }}
          username: ${{ secrets.DROPLET_SSH_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: .
          target: /home/${{ secrets.DROPLET_SSH_USER }}/app
      - name: Build and run Docker container
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.DROPLET_SSH_KEY_LINE }} ${{ secrets.DROPLET_SSH_USER }}@${{ secrets.DROPLET_SSH_HOST }} << EOF
            cd /home/${{ secrets.DROPLET_SSH_USER }}/app
            sudo docker-compose up -d
            exit
          EOF
